version: '3.8'

services:
  backend:
    build: ./backend
    command: python3 manage.py run -h 0.0.0.0
    volumes:
      - ./backend/:/app/
    ports:
      - ${BACKEND_PORT:-8000}:${FRONTEND_PORT:-5000}
    env_file:
      - ./.env.dev
    depends_on:
      - db
    environment:
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT:-5000}
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - ${FRONTEND_PORT:-5000}:3000
    volumes:
      - ./frontend/:/app/
      - ignore:/app/node_modules/
    environment:
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT:-8000}
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
  ignore:
