version: '3.8'

services:
  backend:
    build: ./backend
    command: python3 manage.py run -h 0.0.0.0
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 5000:3000
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:
