import Head from "next/head"

export const Header = (props: {
  header: string;
}) => {
  return (
    <Head>
      <title>{props.header}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}